# This dockerfile is used by the goreleaser, only the relevant binary (OS/arch) is copied in.
FROM alpine:3.19 
RUN apk --no-cache add ca-certificates
COPY oss-chain-bench /usr/local/bin/oss-chain-bench
COPY templates/*.tpl templates/

ENTRYPOINT [ "oss-chain-bench" ]
